events {}

http {

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  upstream grafana { server grafana:3000; }
  upstream nodered { server nodered:1880; }
  upstream influxdb { server influxdb:8086; }
  upstream portainer { server portainer:9000; }

  server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
  }

  # ~ = følgende er regex
  # ^ = match start av streng
  # (?<navn>...) = lagre match av regex i ... som navn
  # .+ = en eller flere (+) av hva som helst (.)
  # \.localhost$ = og det siste som følger må være .localhost (\. angir faktisk dot) $ matcher slutt av streng
  server {
    listen 80;
    server_name ~^(?<service>.+)\.localhost$;

    location / {
      proxy_pass http://$service;
      include ./proxy-common.conf;
    }
  }
  
}
